Progress on Java EE 10 support. Last issue I see locally with guestbook app updated to Java EE 10 web.xml and jsp:
org.apache.jasper.JasperException: The absolute uri: [http://java.sun.com/jsp/jstl/core] cannot be resolved in either web.xml or the jar files deployed with this application


JSTL is a complex ancient beast!